version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local_pass!23
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - .docker-data/mongo:/data/agoro-db