version: 2.1

.directory: &directory
  working_directory: ~/workspace

executors:
  nodejs:
    docker:
      - image: circleci/node:14

.only-main: &only-main
  filters:
    branches:
      only:
        - main


.working_directory: &working_directory
  working_directory: ~/workspace

.container_executor: &container_executor
  docker:
    - image: circleci/python:3.8.8-node

jobs:
  # The checkout job
  checkout-code:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
  bundle-dependencies:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
  code-quality-run-lint:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Run yarn lint'
          command: yarn lint

  code-quality-run-e2e:
    <<: *directory
    docker:
      - image: circleci/node:14
      - image: circleci/mongo:4.4
        environment:
          MONGO_USERNAME: mongouser
          MONGO_PASSWORD: mongopass
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
#      - run:
#          name: MongoDB Install
#          command: |
#            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
#            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
#            sudo apt-get update
#            sudo apt-get install -y mongodb-org-shell
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Create Mongo Super user
          command: |
            mongo --eval 'db.createUser({ user: "user", pwd: "password", roles: [ { role: "root", db: "admin" } ] });'
            mongo -u user -p password --authenticationDatabase admin --eval 'db.getUsers()'  # THIS FAILS
      - run:
          name: 'Run E2E Tests'
          command: yarn run test:e2e

  code-quality-run-unit:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: 'Run Unit Tests'
          command: yarn run test

  build-image:
    <<: *container_executor
    <<: *working_directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: docker_build
          command: |
            time DOCKER_BUILDKIT=1 docker build -t nestjs-playground .

workflows:
  version: 2.1
  pipeline:
    jobs:
      - checkout-code
      - bundle-dependencies:
          requires:
            - checkout-code
      - code-quality-run-lint:
          requires:
            - bundle-dependencies
      - code-quality-run-e2e:
          requires:
            - bundle-dependencies
#      - code-quality-run-unit:
#          requires:
#            - bundle-dependencies
#      - build-image:
#          <<: *only-main