version: 2.1

.directory: &directory
  working_directory: ~/workspace

executors:
  nodejs:
    docker:
      - image: circleci/node:14

.only-main: &only-main
  filters:
    branches:
      only:
        - main


.working_directory: &working_directory
  working_directory: ~/workspace

.container_executor: &container_executor
  docker:
    - image: circleci/python:3.8.8-node

jobs:
  checkout-code:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
  bundle-dependencies:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
  run-lint:
    <<: *directory
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Run yarn lint'
          command: yarn lint

  run-e2e:
    <<: *directory
    docker:
      - image: circleci/node:14
      - image: mongo:4.1.6-xenial
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: circle-test_test
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Waiting for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: 'Run E2E Tests'
          command: yarn run test:e2e --maxWorkers=2

  run-unit:
    <<: *directory
    docker:
      - image: circleci/node:14
      - image: mongo:4.1.6-xenial
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: circle-test_test
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Waiting for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: 'Run Unit Tests'
          command: yarn run test --maxWorkers=2

  build-image:
    <<: *container_executor
    <<: *working_directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: docker_build
          command: |
            time DOCKER_BUILDKIT=1 docker build -t nestjs-playground .

workflows:
  version: 2.1
  pipeline:
    jobs:
      - checkout-code
      - bundle-dependencies:
          requires:
            - checkout-code
      - run-lint:
          requires:
            - bundle-dependencies
      - run-e2e:
          requires:
            - bundle-dependencies
      - run-unit:
          requires:
            - bundle-dependencies
      - build-image:
          <<: *only-main
          requires:
            - code-quality-run-e2e
            - code-quality-run-unit
            - code-quality-run-lint